##############################################################
# Config file for the "SPAD PC"
# Hardware includes: - ANdor Ixion Camera
#                    - C Red Camera
#                    - SPAD Camera
#
# This PC will read the signal from the PWFS, compute the DM commands and sends them to the main RTC PC that 
# runs another instance of pyRTC
##############################################################

loop:
  gain: 0.1
  numDroppedModes: 0
  pokeAmp: 0.01 #
  numItersIM: 5
  affinity: 2
  method: push-pull
  functions:
  - standardIntegrator


trloop:
  gain: 0.1
  numDroppedModes: 0
  pokeAmp: 0.01 #
  numItersIM: 5
  affinity: 2
  method: push-pull
  functions:
  - timeResolvedIntegratorWithTurbulence


trwfs:
  name: MPD_SPAD
  idx: 0
  binning: 1
  exposure: 100 # in 10ns
  nFrames: 48
  nIntegFrames: 1
  width: 32  
  height: 64 
  darkCount: 100
  #darkFile: "res/spad_dark.npy"
  affinity: 3
  functions:
  - expose

wfs:
  name: ANDOR_IXON
  idx: 0
  binning: 1 
  exposure: 0.0625
  width: 128 
  height: 128
  darkCount: 1000
  darkFile: "res/andor_dark.npy"
  affinity: 3
  functions:
  - expose


#TODO  adjust the pupils here for REVOLT
slopes:
  type: PYWFS
  signalType: full_frame
  affinity: 4
  flatNorm: True
  binning: 1
  #Specify where the pupils are and how large for a PYWFS
  pupilsRadius: 17 #5 #17 #17 #4 #9 #15 #17 # 9
  pupils:
  - 22,20 #5,5 #22,20 #5,5 #10,11 #11,11  #21,23 #22,20 # 21,22   11,11
  - 108,20 #26,5 #108,20 #26,5 #53,11 #53, 11 #107,23 #107,20 #  106,22 53,10
  - 21,105 #5,26 #21,105 #5,26 #10,54 #10, 53 #20,108 #22,105 # 21,107 11,53
  - 107,106 #26,26 #107,106 #26,27 #53,54 #53, 54 #107,109 #107,106 # 106,107 54,53
  functions:
  - computeSignal


#TODO  adjust the validSubAps for REVOLT
tr_ff:
  type: TRPYWFS
  signalType: full_frame
  affinity: 4
  validSubApsFile: "res/SPADvalidAps.npy"
  binning: 1
  functions:
  - computeSignal



wfc:
  name: "ALPAO"
  serial: "alpaoHSDM277-15-005"
  numActuators: 277
  numModes: 100
  #flatFile: "/home/revoltuser/pyRTC/REVOLT/wfcShape.npy" #"/home/revoltuser/pyRTC/REVOLT/eyeDoctor_07March2024.fits"
  saveFile: "res/wfcShape.npy"
  #m2cFile:  "res/m2c.npy"
  #floatingActuatorFile: "/home/revoltuser/pyRTC/REVOLT/floatingActuators.npy"
  #floatingInfluenceRadius: 1.5
  affinity: 5
  commandCap: 0.8
  hardwareDelay: 0.001 #seconds
  frameDelay: 0
  functions:
  - sendToHardware